config/routes.rb
DungeonBay::Application.routes.draw do


  resources :users
  resources :campaigns#, :only => [:new, :create, :edit]#, :destroy]
  resources :characters#, :only => [:new, :create, :edit]#, :destroy]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :items,    :only => [:new, :create, :destroy]
  resources :auctions, :only => [:new, :create, :destroy, :index, :show]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  match '/newcampaign', :to => 'campaigns#new'
  match '/newcharacter', :to => 'characters#new'
  match '/newitem', :to => 'items#new'
  match '/newauction', :to => 'auctions#new'
  match '/search_auctions', :to => 'auctions#search'

  root :to => 'pages#home'

  match '/characters/:id/select',  :controller => 'characters', :action => 'select'
  match '/characters/:id/add_gold',  :controller => 'characters', :action => 'add_gold'
  match '/characters/:id/update_gold/',  :controller => 'characters', :action => 'update_gold'
  match '/characters/:id/update_gold/:gold',  :controller => 'characters', :action => 'update_gold'
  match '/campaigns/:id/select',  :controller => 'campaigns', :action => 'select'
  match '/campaigns/:campaign_id/addcharacter/:character_id',  :controller => 'campaigns', :action => 'add_character'
  match '/campaignless',  :controller => 'characters', :action => 'index_campaignless'
  match '/items/:id/select',  :controller => 'items', :action => 'select'
  match '/auctions/:id/bid',  :controller => 'auctions', :action => 'bid'
  match '/auctions/:id/update_bid/',  :controller => 'auctions', :action => 'update_bid'
  match '/auctions/:id/finish_auction/',  :controller => 'auctions', :action => 'finish_auction'
  match '/auctions/:id/buy_it_now/',  :controller => 'auctions', :action => 'buy_it_now'
  match '/search/results/',  :controller => 'auctions', :action => 'search_results'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  encrypted_password :string(255)
#  salt               :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  has_many :characters, :dependent => :destroy, :foreign_key => "owner_id"
  has_many :campaigns, :dependent => :destroy, :foreign_key => "owner_id"
  has_many :auctions, :dependent => :destroy, :foreign_key => "creator_id"

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  :presence     => true,
                    :length       => { :maximum => 50 }
  validates :email, :presence     => true,
                    :format       => { :with => email_regex },
                    :uniqueness   => { :case_sensitive => false }
  # Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence     => true,
                    :confirmation => true,
                    :length       => { :within => 6..40 }

  before_save :encrypt_password

  # Return true if the user's password matches the submitted password.
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  private

  def encrypt_password
    self.salt = make_salt unless has_password?(password)
    self.encrypted_password = encrypt(password)
  end

  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update]
  before_filter :correct_user, :only => [:edit, :update]

  def show
    @user = User.find(params[:id])
    @characters = @user.characters.paginate(:page => params[:page])
    @campaigns = @user.campaigns
    @title = @user.name
  end

  def new
    @user = User.new
    @title = "Sign up"
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      @title = "Sign up"
      @user.password.clear
      @user.password_confirmation.clear
      render 'new'
    end
  end

  def edit
    @title = "Edit user"
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  private

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update", :class => "userupdate_submit" %>
  </div>
<% end %>

<div class="profile">
  <!--[profile pic goes here]-->
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up", :class => "signup_submit" %>
  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
      <th><%= @user.name %></th>
  <tr>
    <td class="main">
      <% unless @campaigns.empty? %>
        <table class="campaigns" summary="User campaigns">
          <th>Campaigns</th>
          <%= render @campaigns %>
        </table>
      <% end %>
      <% unless @user.characters.empty? %>
        <% @in_user_profile = true %>
        <table class="characters" summary="User characters">
          <th>Characters</th>
          <%= render @characters %>
        </table>
        <%= will_paginate @characters %>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %><br />
      <strong>Campaigns</strong> <%= @user.campaigns.count %><br/>
      <strong>Characters</strong> <%= @user.characters.count %><br/>
      <% if signed_in? %>
        <%= link_to "Create a campaign", newcampaign_path, :class => "createcampaign_button round" %><br />
        <%= link_to "Create a character", newcharacter_path, :class => "createcharacter_button round" %><br />
        <% if character_selected? %>
          <strong>Signed in as:</strong> <%= current_character.name %><br />
        <% else %>
          You will need to choose one of your characters for the auction functionality.
        <% end %>
        <% if campaign_selected? %>
          <span class="campaign-options">
            <strong>Campaign selected:</strong> <%= current_campaign.name %><br />
            (this allows you to add 
            <%= link_to("campaignless characters", :controller=>"characters", :action => 'index_campaignless') %>
            to this campaign or 
            <%= link_to("create items", newitem_path) %>
            for this campaign.)
          </span>
        <% end %>
      <% end %>
    </td>
  </tr>
</table>