config/routes.rb
DungeonBay::Application.routes.draw do


  resources :users
  resources :campaigns#, :only => [:new, :create, :edit]#, :destroy]
  resources :characters#, :only => [:new, :create, :edit]#, :destroy]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :items,    :only => [:new, :create, :destroy]
  resources :auctions, :only => [:new, :create, :destroy, :index, :show]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  match '/newcampaign', :to => 'campaigns#new'
  match '/newcharacter', :to => 'characters#new'
  match '/newitem', :to => 'items#new'
  match '/newauction', :to => 'auctions#new'
  match '/search_auctions', :to => 'auctions#search'

  root :to => 'pages#home'

  match '/characters/:id/select',  :controller => 'characters', :action => 'select'
  match '/characters/:id/add_gold',  :controller => 'characters', :action => 'add_gold'
  match '/characters/:id/update_gold/',  :controller => 'characters', :action => 'update_gold'
  match '/characters/:id/update_gold/:gold',  :controller => 'characters', :action => 'update_gold'
  match '/campaigns/:id/select',  :controller => 'campaigns', :action => 'select'
  match '/campaigns/:campaign_id/addcharacter/:character_id',  :controller => 'campaigns', :action => 'add_character'
  match '/campaignless',  :controller => 'characters', :action => 'index_campaignless'
  match '/items/:id/select',  :controller => 'items', :action => 'select'
  match '/auctions/:id/bid',  :controller => 'auctions', :action => 'bid'
  match '/auctions/:id/update_bid/',  :controller => 'auctions', :action => 'update_bid'
  match '/auctions/:id/finish_auction/',  :controller => 'auctions', :action => 'finish_auction'
  match '/auctions/:id/buy_it_now/',  :controller => 'auctions', :action => 'buy_it_now'
  match '/search/results/',  :controller => 'auctions', :action => 'search_results'

end

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>We are a software team from CSU Fullerton's CPSC 473 class, Spring 2012.</p>
<p>The source code for this project is <a href="https://github.com/msphil/DungeonBay">hosted on Github</a>.</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>The source code for this project is <a href="https://github.com/msphil/DungeonBay">hosted on Github</a>.</p>
<p>You can contact the developers through that project page or <a href="mailto:msphil@gmail.com">via e-mail</a>.</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
[Help text goes here]
</p>

app/views/pages/home.html.erb
<% if signed_in? %>
  <table class="front" summary="For signed-in users">
    <tr>
      <td class="auctions-link">
        <%= link_to "Check out all the auctions!", auctions_path, :class => "auctions_button round" %>
        <p />
        ...or search the auctions from the campaign your currently-selected character is in:<br />
        <%= render 'auctions/search' %><br />
      </td>
      <td class="sidebar round">
        <%= render 'shared/user_info' %>
      </td>
    </tr>
  </table>
<% else %>

  <h1>DungeonBay</h1>

  <p>This is the home page for DungeonBay.</p>

  <%= render 'auctions/search' %><br />

  <%= link_to "Check out some auctions!", auctions_path, :class => "auctions_button round" %><br />

  <%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>
<% end %>