config/routes.rb
DungeonBay::Application.routes.draw do


  resources :users
  resources :campaigns#, :only => [:new, :create, :edit]#, :destroy]
  resources :characters#, :only => [:new, :create, :edit]#, :destroy]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :items,    :only => [:new, :create, :destroy]
  resources :auctions, :only => [:new, :create, :destroy, :index, :show]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  match '/newcampaign', :to => 'campaigns#new'
  match '/newcharacter', :to => 'characters#new'
  match '/newitem', :to => 'items#new'
  match '/newauction', :to => 'auctions#new'
  match '/search_auctions', :to => 'auctions#search'

  root :to => 'pages#home'

  match '/characters/:id/select',  :controller => 'characters', :action => 'select'
  match '/characters/:id/add_gold',  :controller => 'characters', :action => 'add_gold'
  match '/characters/:id/update_gold/',  :controller => 'characters', :action => 'update_gold'
  match '/characters/:id/update_gold/:gold',  :controller => 'characters', :action => 'update_gold'
  match '/campaigns/:id/select',  :controller => 'campaigns', :action => 'select'
  match '/campaigns/:campaign_id/addcharacter/:character_id',  :controller => 'campaigns', :action => 'add_character'
  match '/campaignless',  :controller => 'characters', :action => 'index_campaignless'
  match '/items/:id/select',  :controller => 'items', :action => 'select'
  match '/auctions/:id/bid',  :controller => 'auctions', :action => 'bid'
  match '/auctions/:id/update_bid/',  :controller => 'auctions', :action => 'update_bid'
  match '/auctions/:id/finish_auction/',  :controller => 'auctions', :action => 'finish_auction'
  match '/auctions/:id/buy_it_now/',  :controller => 'auctions', :action => 'buy_it_now'
  match '/search/results/',  :controller => 'auctions', :action => 'search_results'

end

app/models/character.rb
# == Schema Information
#
# Table name: characters
#
#  id          :integer         not null, primary key
#  owner_id    :integer
#  campaign_id :integer
#  name        :string(255)
#  description :string(255)
#  gold        :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Character < ActiveRecord::Base
  attr_accessible :name, :description, :img_url

  validates :name, :presence => true, :length => { :within => 1..50 }
  validates :description, :presence => true, :length => { :maximum => 1023 }

  belongs_to :user, :foreign_key => "owner_id"
  has_one :campaign
  has_many :items, :dependent => :destroy, :foreign_key => "owner_id"

  validates :owner_id, :presence => true

  default_scope :order => 'characters.name ASC'

  def campaign_name
    c_id = self.campaign_id
    if (c_id != 0)
      c = Campaign.find_by_id(self.campaign_id)
      unless c.nil? 
        return c.name
      end
    end
    return "[No campaign]"
  end

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_filter :authenticate, :only => [:new, :edit, :update, :add_gold]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :is_gm, :only => [:add_gold, :update_gold]

  def new
    u = current_user
    @title = "Create character"
    @character = u.characters.new
  end

  def create
    @character = Character.new(params[:character])
    @character.owner_id = current_user.id
    @character.gold = 0
    if @character.save
      flash[:success] = "Character created!"
      redirect_to current_user
    else
      render 'new'
    end
  end

  def edit
    @title = "Edit character"
  end

  def show
    @character = Character.find(params[:id])
    @title = @character.name
  end

  def select
    @character = Character.find(params[:id])
    if @character.owner_id == current_user.id
      @title = @character.name + " selected"
      flash[:success] = "Signed in as " + @character.name + "!"
      select_character @character
      redirect_to current_user
    else
      flash[:error] = "You cannot sign in as a character you do not own!"
      redirect_to root_path
    end
  end

  def update
    @character = Character.find(params[:id])
    if @character.update_attributes(params[:character])
      flash[:success] = "Profile updated."
      redirect_to @character
    else
      @title = "Edit character"
      render 'edit'
    end
  end

  def index
    @characters = Character.paginate(:page => params[:page])
    @title = "All characters"
  end

  def index_campaignless
    @characters = Character.where(:campaign_id => nil)#.paginate
    @title = "Characters lacking a campaign"
  end

  def correct_user
    @character = Character.find(params[:id])
    @user = User.find(@character.owner_id)
    redirect_to(root_path) unless current_user?(@user)
  end

  def is_gm
    @character = Character.find(params[:id])
    if @character.campaign_id != current_campaign.id and current_campaign.owner_id != current_user.id
      redirect_to root_path
    end
  end

  def add_gold
    @character = Character.find(params[:id])
    @title = "Add gold to " + @character.name
  end

  def update_gold
    @character = Character.find(params[:id])
    new_gold = params[:gold].to_i
    @character.gold += new_gold
    @character.save
    redirect_to current_campaign
  end

end

app/helpers/characters_helper.rb
module CharactersHelper


end

app/views/characters/_character.html.erb
<tr>
  <td class="character">
    <span class="portrait"><img src="<%= character.img_url %>" /></span><br />
    <span class="name"><%= link_to character.name, character %></span><br />
    <span class="description"><%= character.description %></span><br />
    <% unless @skip_campaign_name %>
      <span class="campaign"><strong>Campaign:</strong> <%= character.campaign_name %></span>
    <% end %>
    <% if signed_in? %>
      <% if !character.campaign_id %>
        <% if campaign_selected? %>
          <br />
          <%= link_to("Add this character to " + current_campaign.name, :controller=>"campaigns", :action => 'add_character', :character_id => character.id, :campaign_id => current_campaign.id) %>
        <% end %>
      <% end %>
    <% end %>
  </td>
</tr>
<% if @in_user_profile and signed_in? %>
<tr>
  <% if character_selected? and current_character != character %>
    <% if character.owner_id == current_user.id %>
      <td class="select">
        <%= link_to("Choose this character", :controller=>"characters", :action => 'select', :id => character.id) %>
      </td>
    <% end %>
  <% else %>
      <td class="select">
        You are currently signed in as this character
      </td>
  <% end %>
</tr>
<% end %>
<% if @on_campaign_page %>
  <% if signed_in? and current_user.id == @campaign.owner_id %>
  <tr>
    <td class="gm_edit">
      <%= link_to("Add gold to this character", :controller=>"characters", :action => 'add_gold', :id => character.id) %>
    </td>
  </tr>
  <% end %>
<% end %>

app/views/characters/add_gold.html.erb
<h1>Add gold to <%= @character.name %></h1>

<% form_url = "/characters/" + @character.id.to_s + "/update_gold/" %>
<form action="<%= form_url %>" method="post">
  <div class="field">
    Amount to add: <input type="text" name="gold">
  </div>
  <div class="actions">
    <input type="submit" value="Add!" class="addgold_submit round">
  </div>
</form>

app/views/characters/edit.html.erb
<h1>Edit character</h1>

<%= form_for(@character) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br />
    <%= f.text_field :img_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit "Update", :class => "characterupdate_submit" %>
  </div>
<% end %>

app/views/characters/index.html.erb
<h1>All users</h1>

<%= will_paginate %>

<table class="characters">
  <%= render @characters %>
</table>

<%= will_paginate %>

app/views/characters/index_campaignless.html.erb
<h1>All users</h1>

<!--< %= will_paginate %>-->

<table class="characters">
  <%= render @characters %>
</table>

<!--< %= will_paginate %>-->

app/views/characters/new.html.erb
<h1>Create a Character</h1>

<%= form_for(@character) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label "Image URL" %><br />
    <%= f.text_field :img_url %>
  </div>
  <div class="actions">
    <%= f.submit "Create!", :class => "newcharacter_submit" %>
  </div>
<% end %>

app/views/characters/show.html.erb
<table class="character-profile" summary="Profile information">
  <h1><%= @character.name %></h1>
  <tr>
    <td class="main">
      <table class="character-summary" summary="Character information">
        <tr>
          <td>
            <img src="<%= @character.img_url %>" />
          </td>
          <td>
            <%= @character.description %>
          </td>
        </tr>
        <% if signed_in? %>
          <% if current_user.id == @character.owner_id %>
            <tr>
              <td>
                <%= link_to "Edit character", edit_character_path(@character) %>
              </td>
            </tr>
          <% end %>
        <% end %>
        <tr>
          <td>
            <table>
              <th>Items</th>
              <%= render @character.items %>
            </table>
          </td>
        </tr>
      </table>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @character.name %><br />
      <strong>URL</strong>  <%= link_to character_path(@character), @character %><br />
      <% owner = User.find(@character.owner_id) %>
      <strong>User</strong>  <%= link_to owner.name, user_path(owner) %><br />
      <% if signed_in? and owner == current_user %>
      <strong>Gold</strong>  <%= @character.gold %><br />
      <% end %>
    </td>
  </tr>
</table>